services:
  solovey-ui:
    image: ghcr.io/malenkiysolovey/solovey-ui
    container_name: solovey-ui
    hostname: "solovey-ui"
    network_mode: host
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    entrypoint: "./entrypoint.sh"
