package runtime

import (
	"context"
	"errors"
	"net"
	"net/netip"
	"strings"
	"sync/atomic"
	"time"

	corelogging "github.com/MalenkiySolovey/solovey-ui/core/logging"
	"github.com/MalenkiySolovey/solovey-ui/util/common"
	"github.com/MalenkiySolovey/solovey-ui/util/redact"
	"github.com/sagernet/sing-box/adapter"
	boxservice "github.com/sagernet/sing-box/adapter/service"
	"github.com/sagernet/sing-box/daemon"
	"github.com/sagernet/sing-box/log"
	"github.com/sagernet/sing-box/option"
	boxapi "github.com/sagernet/sing-box/service/api"
	"github.com/sagernet/sing/common/json/badoption"
	"github.com/sagernet/sing/service"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/protobuf/types/known/emptypb"
)

const privateAPITag = "__solovey_runtime_api"
const runtimeAPITimeout = 3 * time.Second
const maxRuntimeMessageBytes = 2 << 20

var (
	ErrRuntimeAPIUnavailable = errors.New("runtime_api_unavailable")
	ErrStaleGeneration       = errors.New("stale_generation")
	ErrRuntimeLimit          = errors.New("runtime_limit_exceeded")
)

// Only the lifecycle owner holds this credential. It is never serialized,
// persisted, placed in the public config builder, or supplied by an operator.
type privateAPI struct {
	generation  string
	endpoint    string
	secret      string
	reservation net.Listener
	conn        *grpc.ClientConn
	rpc         daemon.StartedServiceClient
}

func (*privateAPI) String() string   { return "private runtime API [REDACTED]" }
func (*privateAPI) GoString() string { return "private runtime API [REDACTED]" }

func preparePrivateAPI(ctx context.Context, options *option.Options) (context.Context, *privateAPI, error) {
	for _, item := range options.Services {
		if item.Type == "api" || item.Tag == privateAPITag {
			return ctx, nil, errors.New("private runtime API is generated by the lifecycle owner")
		}
	}
	for _, item := range options.Inbounds {
		if item.Tag == privateAPITag {
			return ctx, nil, errors.New("reserved runtime tag")
		}
	}
	for _, item := range options.Outbounds {
		if item.Tag == privateAPITag {
			return ctx, nil, errors.New("reserved runtime tag")
		}
	}
	for _, item := range options.Endpoints {
		if item.Tag == privateAPITag {
			return ctx, nil, errors.New("reserved runtime tag")
		}
	}
	secret, err := common.SecureRandom(64)
	if err != nil {
		return ctx, nil, errors.New("runtime credential generation failed")
	}
	generation, err := common.RandomUUID()
	if err != nil {
		return ctx, nil, errors.New("runtime identity generation failed")
	}
	// The OS chooses an unused high loopback port. Keep the reservation through
	// construction; release just before official service startup. A bind race is
	// a failed candidate, never a retry on a different/public endpoint.
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return ctx, nil, errors.New("private runtime listener reservation failed")
	}
	api := &privateAPI{generation: generation, endpoint: listener.Addr().String(), secret: secret, reservation: listener}
	port := uint16(listener.Addr().(*net.TCPAddr).Port)
	address := badoption.Addr(netip.MustParseAddr("127.0.0.1"))
	options.Services = append(options.Services, option.Service{Type: "api", Tag: privateAPITag, Options: &option.APIServiceOptions{
		ListenOptions:            option.ListenOptions{Listen: &address, ListenPort: port},
		Secret:                   secret,
		AccessControlAllowOrigin: badoption.Listable[string]{"https://runtime.solovey.invalid"},
	}})
	// Only this fresh private constructor registry enables the official service.
	// Product/entity registries retain the raw API editor's negative capability.
	var constructed atomic.Bool
	boxservice.Register[option.APIServiceOptions](service.FromContext[adapter.ServiceRegistry](ctx).(*boxservice.Registry), "api",
		func(ctx context.Context, logger log.ContextLogger, tag string, generated option.APIServiceOptions) (adapter.Service, error) {
			if tag != privateAPITag || generated.Secret != secret || generated.Secret == "" || generated.Listen == nil ||
				netip.Addr(*generated.Listen) != netip.MustParseAddr("127.0.0.1") || generated.ListenPort != port ||
				generated.Dashboard != nil || generated.TLS != nil || generated.AccessControlAllowPrivateNetwork ||
				len(generated.AccessControlAllowOrigin) != 1 || generated.AccessControlAllowOrigin[0] != "https://runtime.solovey.invalid" ||
				!constructed.CompareAndSwap(false, true) {
				return nil, errors.New("private runtime API constructor policy rejected")
			}
			return boxapi.NewService(ctx, logger, tag, generated)
		})
	return corelogging.WithSecrets(ctx, []string{secret}), api, nil
}

func (a *privateAPI) releaseReservation() error {
	if a.reservation == nil {
		return nil
	}
	listener := a.reservation
	a.reservation = nil
	return listener.Close()
}

type privateBearer struct{ secret string }

func (b privateBearer) GetRequestMetadata(context.Context, ...string) (map[string]string, error) {
	if b.secret == "" {
		return nil, ErrRuntimeAPIUnavailable
	}
	return map[string]string{"authorization": "Bearer " + b.secret}, nil
}
func (privateBearer) RequireTransportSecurity() bool { return false } // loopback only

func (a *privateAPI) connect(ctx context.Context) error {
	conn, err := grpc.NewClient("passthrough:///"+a.endpoint,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithPerRPCCredentials(privateBearer{a.secret}),
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(maxRuntimeMessageBytes)))
	if err != nil {
		return ErrRuntimeAPIUnavailable
	}
	a.conn, a.rpc = conn, daemon.NewStartedServiceClient(conn)
	probeCtx, cancel := context.WithTimeout(ctx, runtimeAPITimeout)
	defer cancel()
	health, err := grpc_health_v1.NewHealthClient(conn).Check(probeCtx, &grpc_health_v1.HealthCheckRequest{Service: daemon.StartedService_ServiceDesc.ServiceName})
	if err != nil || health.Status != grpc_health_v1.HealthCheckResponse_SERVING {
		return ErrRuntimeAPIUnavailable
	}
	version, err := a.rpc.GetVersion(probeCtx, &emptypb.Empty{})
	if err != nil || version.Version == "" {
		return ErrRuntimeAPIUnavailable
	}
	stream, err := a.rpc.SubscribeServiceStatus(probeCtx, &emptypb.Empty{})
	if err != nil {
		return ErrRuntimeAPIUnavailable
	}
	status, err := stream.Recv()
	if err != nil || status.Status != daemon.ServiceStatus_STARTED {
		return ErrRuntimeAPIUnavailable
	}
	return nil
}

func (a *privateAPI) safeError(err error) error {
	if err == nil {
		return nil
	}
	return errors.New(redact.String(strings.ReplaceAll(err.Error(), a.secret, redact.Marker)))
}

func (a *privateAPI) close() {
	_ = a.releaseReservation()
	if a.conn != nil {
		_ = a.conn.Close()
	}
	a.conn, a.rpc = nil, nil
	a.secret = ""
}
