package fronting

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"strings"
	"time"

	hostresources "github.com/MalenkiySolovey/solovey-ui/componenthost/resources"
)

const (
	fixedL4ConnectTimeoutV2 = "5s"
	fixedL4SessionTimeoutV2 = "1h"
)

type FixedL4CandidateV2 struct {
	Revision       string
	SHA256         string
	Bytes          []byte
	CanonicalInput []byte
	Listener       protectionListenerV2
	Backend        hostresources.FrontingBackendEndpointV1
	UpstreamID     string
}

type protectionListenerV2 struct {
	Address string `json:"address"`
	Port    int    `json:"port"`
}

type fixedL4CandidateBindingV2 struct {
	Schema                   string                      `json:"schema"`
	PlanDigest               string                      `json:"planDigest"`
	Strategy                 FrontingStrategy            `json:"strategy"`
	RuntimeIdentityRevision  string                      `json:"runtimeIdentityRevision"`
	CapabilityRevision       string                      `json:"capabilityRevision"`
	SocketClaimRevision      string                      `json:"socketClaimRevision"`
	ConfigurationRevision    string                      `json:"configurationRevision"`
	TopologyRevision         string                      `json:"topologyRevision"`
	ListenerFactRevision     string                      `json:"listenerFactRevision"`
	ManagementRevision       string                      `json:"managementRevision"`
	BackendReferenceRevision string                      `json:"backendReferenceRevision"`
	BackendEndpointRevision  string                      `json:"backendEndpointRevision"`
	BackendAddress           string                      `json:"backendAddress"`
	BackendPort              uint16                      `json:"backendPort"`
	BackendFamily            hostresources.AddressFamily `json:"backendFamily"`
	ProxyMode                hostresources.ProxyMode     `json:"proxyMode"`
	ConnectTimeout           string                      `json:"connectTimeout"`
	SessionTimeout           string                      `json:"sessionTimeout"`
}

// RenderFixedL4CandidateV2 accepts no address text. The only destination is
// recovered from the exact current provider fact and exact plan reference.
func RenderFixedL4CandidateV2(plan FrontingStrategyPlanV2, fact hostresources.FrontingBackendFactV1, now time.Time) (FixedL4CandidateV2, error) {
	if err := validateFixedL4PlanShapeV2(plan, now); err != nil {
		return FixedL4CandidateV2{}, err
	}
	reference := plan.Targets.BackendReferences[0]
	backend, err := hostresources.ResolveFrontingBackendEndpointV1(reference, fact, now)
	if err != nil {
		return FixedL4CandidateV2{}, errors.New("backend_reference_stale")
	}
	binding := fixedL4CandidateBindingV2{
		Schema: "solovey-ui/fixed-l4-candidate/v2", PlanDigest: plan.CanonicalPlanDigest, Strategy: plan.Strategy.Selected,
		RuntimeIdentityRevision: plan.Runtime.IdentityRevision, CapabilityRevision: plan.StrategyCapabilityRevision,
		SocketClaimRevision: plan.PublicSocket.ClaimRevision, ConfigurationRevision: plan.PublicSocket.CurrentConfigurationRevision,
		TopologyRevision: plan.PublicSocket.TopologyOwnershipEligibilityRevision, ListenerFactRevision: plan.PublicSocket.ListenerSocketFactRevision,
		ManagementRevision: plan.PublicSocket.ManagementExclusionRevision, BackendReferenceRevision: reference.CanonicalReferenceRevision,
		BackendEndpointRevision: reference.EndpointRevision, BackendAddress: backend.Address.String(), BackendPort: backend.Port,
		BackendFamily: backend.AddressFamily, ProxyMode: plan.Targets.SelectedProxyMode,
		ConnectTimeout: fixedL4ConnectTimeoutV2, SessionTimeout: fixedL4SessionTimeoutV2,
	}
	canonical, err := json.Marshal(binding)
	if err != nil {
		return FixedL4CandidateV2{}, errors.New("candidate_invalid")
	}
	revision := v2Revision(binding)
	upstreamID := "solovey_l4_" + revision[:24]
	listen := net.JoinHostPort(plan.PublicSocket.CanonicalBind, fmt.Sprint(plan.PublicSocket.PublicPort))
	backendAddress := net.JoinHostPort(backend.Address.String(), fmt.Sprint(backend.Port))
	var output strings.Builder
	output.Grow(768)
	output.WriteString("# generated by Solovey Server Protection; do not edit\n")
	output.WriteString("# solovey-strategy:L4_ONE_TO_ONE_FRONTING\n")
	output.WriteString("# solovey-plan:")
	output.WriteString(plan.CanonicalPlanDigest)
	output.WriteString("\n# solovey-revision:")
	output.WriteString(revision)
	output.WriteString("\nupstream ")
	output.WriteString(upstreamID)
	output.WriteString(" {\n  server ")
	output.WriteString(backendAddress)
	output.WriteString(";\n}\n\nserver {\n  listen ")
	output.WriteString(listen)
	output.WriteString(";\n  proxy_connect_timeout ")
	output.WriteString(fixedL4ConnectTimeoutV2)
	output.WriteString(";\n  proxy_timeout ")
	output.WriteString(fixedL4SessionTimeoutV2)
	output.WriteString(";\n")
	if plan.Targets.SelectedProxyMode == hostresources.ProxyModeOn {
		output.WriteString("  proxy_protocol on;\n")
	}
	output.WriteString("  proxy_pass ")
	output.WriteString(upstreamID)
	output.WriteString(";\n}\n")
	data := []byte(output.String())
	candidate := FixedL4CandidateV2{Revision: revision, SHA256: fixedL4DigestV2(data), Bytes: data, CanonicalInput: canonical,
		Listener: protectionListenerV2{Address: plan.PublicSocket.CanonicalBind, Port: int(plan.PublicSocket.PublicPort)}, Backend: backend, UpstreamID: upstreamID}
	if err := ValidateFixedL4CandidateV2(candidate, plan); err != nil {
		return FixedL4CandidateV2{}, err
	}
	return candidate, nil
}

func ValidateFixedL4CandidateV2(candidate FixedL4CandidateV2, plan FrontingStrategyPlanV2) error {
	if len(candidate.Bytes) > MaxFutureCandidateBytesV1 {
		return errors.New("candidate_too_large")
	}
	if len(candidate.Bytes) == 0 || candidate.SHA256 != fixedL4DigestV2(candidate.Bytes) ||
		!frontingHexV2(candidate.Revision) || candidate.UpstreamID != "solovey_l4_"+candidate.Revision[:24] {
		return errors.New("candidate_invalid")
	}
	text := string(candidate.Bytes)
	lower := strings.ToLower(text)
	for _, forbidden := range []string{"$", "resolver ", "map ", "regex", "ssl_preread", "ssl_certificate", "ssl_certificate_key", "listen  udp", " unix:", "include ", "backup", "proxy_next_upstream", "server_name", "alpn", "host", "location ", "http {"} {
		if strings.Contains(lower, forbidden) {
			return errors.New("candidate_invalid")
		}
	}
	if strings.Count(lower, "upstream ") != 1 || strings.Count(lower, "server {") != 1 || strings.Count(lower, "proxy_pass ") != 1 ||
		strings.Count(lower, "  listen ") != 1 || strings.Count(lower, "  server ") != 1 ||
		strings.Contains(lower, "proxy_pass "+"$") {
		return errors.New("candidate_invalid")
	}
	wantProxy := plan.Targets.SelectedProxyMode == hostresources.ProxyModeOn
	if strings.Contains(lower, "proxy_protocol on;") != wantProxy || strings.Count(lower, "proxy_protocol on;") > 1 {
		return errors.New("proxy_protocol_mismatch")
	}
	wantListen := "listen " + net.JoinHostPort(plan.PublicSocket.CanonicalBind, fmt.Sprint(plan.PublicSocket.PublicPort)) + ";"
	wantBackend := "server " + net.JoinHostPort(candidate.Backend.Address.String(), fmt.Sprint(candidate.Backend.Port)) + ";"
	if !strings.Contains(text, wantListen) || !strings.Contains(text, wantBackend) || !strings.Contains(text, "proxy_pass "+candidate.UpstreamID+";") {
		return errors.New("candidate_invalid")
	}
	return nil
}

func validateFixedL4PlanShapeV2(plan FrontingStrategyPlanV2, now time.Time) error {
	if plan.Validate() != nil || plan.ExpiresAt <= now.UTC().Unix() || plan.Strategy.Desired != StrategyL4OneToOne ||
		plan.Strategy.Selected != StrategyL4OneToOne || plan.Strategy.Actual != FrontingActualNotAppliedV2 ||
		plan.Safety.Projection != plan.Strategy || len(plan.Safety.Blocks) != 0 || len(plan.Safety.ReasonCodes) != 0 ||
		len(plan.Targets.BackendReferences) != 1 || len(plan.Targets.FallbackReferences) != 0 || len(plan.Targets.ReferenceRevisions) != 1 ||
		len(plan.Selectors.Tuples) != 0 || len(plan.Selectors.TargetRevisions) != 0 || plan.Selectors.Default.Policy != SelectorDefaultReject ||
		plan.Selectors.Default.TargetReferenceRevision != "" || plan.Targets.SelectedProxyMode != hostresources.ProxyModeOff && plan.Targets.SelectedProxyMode != hostresources.ProxyModeOn {
		return errors.New("candidate_invalid")
	}
	return nil
}

func fixedL4DigestV2(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}
