package fronting

import (
	"fmt"
	"net"
	"sort"
	"strings"

	hostresources "github.com/MalenkiySolovey/solovey-ui/componenthost/resources"
)

// renderNginx emits a generated include only. Selector values are fixed
// upstream names; SNI and ALPN are never used as destinations. Preview is pure
// and the exact same bytes become the helper-validated managed candidate.
func renderNginx(model canonicalPreview, resources map[string]hostresources.ProtectableResource, fallback *hostresources.ProtectableResource) string {
	var output strings.Builder
	output.WriteString("# generated by Solovey Server Protection; do not edit\n")
	output.WriteString("# managed candidate: activation is restricted-helper only\n")
	upstreamNames := map[string]string{}
	for _, route := range model.Routes {
		upstreamNames[route.Target] = upstreamName(route.Target)
	}
	if fallback != nil {
		upstreamNames[fallback.ID] = upstreamName(fallback.ID)
	}
	ids := make([]string, 0, len(upstreamNames))
	for id := range upstreamNames {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		resource := resources[id]
		output.WriteString("upstream ")
		output.WriteString(upstreamNames[id])
		output.WriteString(" {\n")
		output.WriteString("  server ")
		output.WriteString(net.JoinHostPort(resource.Listen, fmt.Sprint(resource.Port)))
		output.WriteString(";\n}\n\n")
	}
	defaultTarget := ""
	if fallback != nil {
		defaultTarget = upstreamNames[fallback.ID]
	}
	output.WriteString("map \"$ssl_preread_server_name|$ssl_preread_alpn_protocols\" $solovey_static_upstream {\n")
	if defaultTarget == "" {
		output.WriteString("  default \"\";\n")
	} else {
		output.WriteString("  default ")
		output.WriteString(defaultTarget)
		output.WriteString(";\n")
	}
	for _, route := range model.Routes {
		for _, sni := range route.SNI {
			if len(route.ALPN) == 0 {
				output.WriteString("  \"")
				output.WriteString(sni)
				output.WriteString("|\" ")
				output.WriteString(upstreamNames[route.Target])
				output.WriteString(";\n")
				continue
			}
			for _, alpn := range route.ALPN {
				output.WriteString("  \"")
				output.WriteString(sni)
				output.WriteString("|")
				output.WriteString(alpn)
				output.WriteString("\" ")
				output.WriteString(upstreamNames[route.Target])
				output.WriteString(";\n")
			}
		}
	}
	output.WriteString("}\n\n")
	listens := map[string]ListenSpec{}
	for _, route := range model.Routes {
		listens[fmt.Sprintf("%s:%d", route.Listen.Address, route.Listen.Port)] = route.Listen
	}
	ordered := make([]ListenSpec, 0, len(listens))
	for _, listen := range listens {
		ordered = append(ordered, listen)
	}
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].Port != ordered[j].Port {
			return ordered[i].Port < ordered[j].Port
		}
		return ordered[i].Address < ordered[j].Address
	})
	for _, listen := range ordered {
		output.WriteString("server {\n  listen ")
		output.WriteString(renderListen(listen))
		output.WriteString(";\n  ssl_preread on;\n")
		for _, route := range model.Routes {
			if route.Listen == listen && route.Proxy {
				output.WriteString("  proxy_protocol on;\n")
				break
			}
		}
		if defaultTarget == "" {
			output.WriteString("  return 444;\n")
		} else {
			output.WriteString("  proxy_pass $solovey_static_upstream;\n")
		}
		output.WriteString("}\n\n")
	}
	return strings.TrimRight(output.String(), "\n") + "\n"
}

func upstreamName(id string) string {
	var output strings.Builder
	output.WriteString("solovey_target_")
	for _, value := range id {
		if (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9') {
			output.WriteRune(value)
		} else {
			output.WriteByte('_')
		}
	}
	return output.String()
}

func renderListen(value ListenSpec) string {
	if value.Address == "*" {
		return fmt.Sprint(value.Port)
	}
	return net.JoinHostPort(value.Address, fmt.Sprint(value.Port))
}
