// Code generated by scripts/openwrt-persistence-authority.mjs; DO NOT EDIT.
// Source: workspace upstreams/OPENWRT_REFERENCE_LOCK.md A1/A2 and pinned fstools recipe.
package openwrt

func selectedPersistenceAuthority() PersistenceAuthority {
	return PersistenceAuthority{
		OpenWrtRelease: "25.12.5",
		OpenWrtSource:  "f0a60eee2fe051741c643ea6118718aae1ef17fb",
		FSToolsSource:  "16718b6e3c0fc7db7be6ae5848db0eae88ac8a8b",
	}
}
