import { describe, expect, it } from 'vitest'
import type { UDPGuardCapability, UDPGuardPlan } from './udpGuardTypes'
import { udpCanPrepare, udpCapabilityBadges, udpPlanReference } from './udpGuardLogic'

const plan = { planId:'udp-plan:one',planDigest:'a'.repeat(64),resourceId:'core:inbound:1',endpointId:'claim:1',capabilityRevision:'b'.repeat(64),buildFeatureRevision:'c'.repeat(64),claim:{claimRevision:'d'.repeat(64),protocol:'udp',addressFamily:'ipv4',configuredBind:'0.0.0.0',exposure:'PUBLIC',port:443,ownerRevision:'e'.repeat(64)},strategyClass:'PLAIN_UDP',desiredPolicy:'UDP_DIRECT_GUARDED',selectedStrategy:'UDP_DIRECT_GUARDED',actualState:'NOT_APPLIED',applyGate:'EXPERIMENTAL_DEFAULT_OFF',firewallBaselineRevision:'f'.repeat(64),healthRevision:'1'.repeat(64),flowPolicy:{revision:'2'.repeat(64),rateProfile:'BALANCED_V1',cardinalityProfile:'BOUNDED_4096_V1',conntrackPolicy:'ADVISORY_NEW_FLOW_V1',icmpPolicy:'PRESERVE_ICMP_AND_ICMPV6_V1'},blockCodes:[],warningCodes:[]} satisfies UDPGuardPlan

describe('UDP guard UI contracts',()=>{
	it('sends only server-authored semantic identities',()=>{expect(udpPlanReference(plan)).toEqual({planId:plan.planId,planDigest:plan.planDigest,resourceId:plan.resourceId,endpointId:plan.endpointId,capabilityRevision:plan.capabilityRevision,claimRevision:plan.claim.claimRevision,healthRevision:plan.healthRevision,firewallBaselineRevision:plan.firewallBaselineRevision,strategy:'UDP_DIRECT_GUARDED',policyRevision:plan.flowPolicy.revision});expect(JSON.stringify(udpPlanReference(plan))).not.toContain('configuredBind')})
	it('keeps blocked and prepared states non-actionable',()=>{expect(udpCanPrepare(plan)).toBe(true);expect(udpCanPrepare({...plan,applyGate:'BLOCKED',blockCodes:['BLOCKED_MISSING_HEALTH']})).toBe(false);expect(udpCanPrepare({...plan,actualState:'PREPARED'})).toBe(false)})
	it('distinguishes shipped, inspection-only, association and unsupported facts',()=>{const base={resourceId:'core:inbound:1',inboundType:'shadowsocks',strategyClass:'PLAIN_UDP',shippingStatus:'SHIP',effectiveNetworks:['udp'],configured:true,observed:true,dependentAssociation:false,buildFeatureState:'SUPPORTED',authenticationPresent:true,tlsPresent:false,protocolOwnedZeroRtt:false,protocolOwnedMigration:false,actualState:'NOT_APPLIED',applyGate:'EXPERIMENTAL_DEFAULT_OFF'} satisfies UDPGuardCapability;expect(udpCapabilityBadges(base)).toEqual(['CONFIGURED','OBSERVED','SHIP','UDP']);expect(udpCapabilityBadges({...base,inboundType:'direct',shippingStatus:'INSPECTION_ONLY'})).toContain('INSPECTION_ONLY');expect(udpCapabilityBadges({...base,inboundType:'mixed',strategyClass:'PROXY_UDP_ASSOCIATION',shippingStatus:'NOT_SHIPPED',dependentAssociation:true})).toContain('PROXY_ASSOCIATION_ONLY');expect(udpCapabilityBadges({...base,inboundType:'h2',strategyClass:'UNSUPPORTED',shippingStatus:'NOT_SHIPPED'})).toContain('UNSUPPORTED')})
})
